### PR TITLE
AdvSample > Wind Turbine DataView > Type/Stream Creation

### PR DESCRIPTION
**Pull request by kelseyduffy**
Added notebook entries at the end, just before the prediction data is written to OCS, that create the type and the stream using the OCSClient library. Creating the type and stream makes logical sense within the notebook after the ML portion that builds the model since, theoretically, only at that point do you know from the ML model which fields are important for the prediction. 

The type/stream creation demonstrates OCS Client library usage, pulled mostly from the basic samples > SDS.

### CODE REVIEW

**Comment by cfoisy-osisoft** [comment]
I haven't look at the notebook diff but you may want to do the following within this PR:

- remove the autosave notebook directory .ipynb_checkpoints (good candidate for .gitignore)
- delete the binary model file WT_ActivePower_model.sav generated by the notebook

**Comment by cfoisy-osisoft** [comment]
Suggestion: to make output easier to scroll, you could replace "data" by "data[:5]" in cell[3] to truncate it yourself (it's already truncated but arbitrarily and kept too long, imho)

**Comment by kelseyduffy** [comment]
Figured out why the tests were failing, and we need to discuss it further on how to best approach it, but this most recent commit should (?) pass the tests (or at least not fail the same way). I also truncated the output at each step (except for the weather json response) to keep the notebook shorter, per @cfoisy-osisoft recommendation.

**Comment by kelseyduffy** [comment]
as a reminder, this is not ready for PR review yet, but should be soon. Rather than close the PR, I'll make a couple more commits this week and we should be good.

**Comment by kelseyduffy** [comment]
for some reason the dataview.json did not create the data view successfully, but it did create the other types and streams, and it uploaded all the (meta)data. I'll look into this tomorrow.

**Comment by kelseyduffy** [comment]
this PR should (finally) be ready for review. 

- I removed the Type and Stream for the created predicted power values from the bulkuploader section and moved them into the jupyter notebook itself following the creation of the power prediction algorithm. 
- Also changed the default appsettings file for this sample's bulk uploaded data since it was missing the property for the dataview, so the data view did not get created.
- I truncated some of the outputs to keep the notebook a little shorter

**Review by cbardini — APPROVED** [review]

**Review by derekendres — APPROVED** [review]
is there a need to make the readme clearer?  maybe adding a step in the readme in https://github.com/osisoft/OSI-Samples-OCS/tree/Adv_DataViews_WindTurbine_AddTypeStreamCreation/advanced_samples/DataViewWind/Jupyter#getting-started  saying to get the data.  not required, i just remember helping point this out to people in the past

**Comment by kelseyduffy** [comment]
@derekendres you're right, I forgot to switch the two sections like I had intended. I moved the Data Overview section to be underneath the Getting Started section, so that if you jump to the Getting Started section right off the bat, you still get to the Data Overview section

**Pull request merged**
