### PR TITLE
Python Library: Use BaseClient request method

### PR DESCRIPTION
**Pull request by dcbroad3**

### CODE REVIEW

**Comment by derekendres** [comment]
@cfoisy-osisoft

**Comment by cfoisy-osisoft** [comment]
@derekendres If https://pypi.org/project/typeguard/library fits the company requirements, you could get rid of a lot of the argument checking code. For example we use it for the academic hub library:

    @typechecked
    def dataviews_interpolated_pd(
        self,
        namespace_id: str,
        dv_ids: List[str],
        start_index: str,
        end_index: str,
        interval: str,
        count: int = MAX_COUNT,
        workers: int = 3,
        verbose: bool = False,
        raw: bool = False,
        skip_sort: bool = False,
        debug: bool = False,
    ):
        df = pd.DataFrame()

All the types are from the standard library `typing` since 3.5 (https://docs.python.org/3/library/typing.html). This way no need to check if an argument is None or of the wrong type. From a user perspective, you get feedback right away at the method call instead of latter on when something breaks.

**Comment by derekendres** [comment]
We probably should look at that.  I think thats out of the bounds of what would we do with the particular PR and WI.  I do think we should probably be doing at least the hints of  what is expected for the type as per PEP 484 https://docs.python.org/3/library/typing.html.

**Comment by derekendres** [comment]
As a follow up comment, I never know what constructs like this are taking paradigms and things expected in a strongly typed language and trying to apply that to a language that likes to quack...

**Comment by cfoisy-osisoft** [comment]
Type hints are a very good step since it documents the API. If and how people wants to enforce it (mypy or else) would be their choice. I'm all for quacking but sparingly, and yeah it's not clear where you land on the fully untyped - static typing axis.

**Pull request merged**
